[package]
name = "escrow_program"
version = "0.1.0"
edition = "2021"

[lib]
name = "escrow_program"
crate-type = ["cdylib", "lib"]

[dependencies]
solana-program = "2.2.1"
borsh = "1.5.7"
borsh-derive = "1.5.7"